// #ifndef COMMON_OP_CODE_H
// #define COMMON_OP_CODE_H

// enum {OP_CODE_SETUP = "1", OP_CODE_QUIT = "2", OP_CODE_CREATE = "3", OP_CODE_RESERVE = "4", OP_CODE_SHOW = "5", OP_CODE_EMS_LIST_EVENTS = 6};

// #endif COMMON_OP_CODE_H
